#!/bin/bash

if (dpkg -s samba) #kontrollime kas Samba on või ei ole, kui pole siis installime, Ütleme kasutajale ikka ka.
 then
    echo "Samba on juba installitud, see on armas =)"
 else
    sudo apt-get --assume-yes install samba #meelega on sudo scriptis, juhuks kui keegi kolmas püüab midagi teha kuid tal puudub vastav pädevus.
    echo "Kle, installisin sulle selle samba asja kiirelt, ää pahanda."
fi

if ([ -d $1 ]) #Kontrollima kas kaust on või ei ole, ütleme kasutajale ka
  then
    echo "kaust on juba olemas, Palju õnne!"
  else
    mkdir -p -v $1 # -v kirjutame kasutajale välja ka, mis kaust sai loodud
    echo "loome kausta juba siis"
fi

if (getent group $2) #kontrollime kas kasutajagrupp on olemas või mitte, ütleme kasutajale ka
  then
    echo "See kasutajagrupp olemas!"
  else
    echo "gruppi vaja, KOHE!"
    sudo groupadd $2
fi

if( [ -r /etc/samba/smb.conf ]) #vaatame igaks juhuks üle, kas samba conf on ikka seal kus ta peab olema.
  then
    sudo cp /etc/samba/smb.conf /etc/samba/smb1.conf #teeme koopia millega ise mängime
    sudo chmod 777 /etc/samba/smb1.conf #suur suur, security hole!!!
    #Lisa read (append) smb1.conf
   if([ -z $3 ]) #vaatame kas kasutaja andis meile share'i nime ka või lahmib niisama
     then
       echo "[jaga $RANDOM]" >> /etc/samba/smb1.conf
     else
       echo "[$3]" >> /etc/samba/smb1.conf
   fi
DATE=`date +%Y-%m-%d:%H:%M:%S`
    echo "comment= Loodud $DATE" >> /etc/samba/smb1.conf
    echo "path=$1" >> /etc/samba/smb1.conf
    echo "writable=yes" >> /etc/samba/smb1.conf
    echo "valid users=@$2" >> /etc/samba/smb1.conf
    echo "force group=$2" >> /etc/samba/smb1.conf
    echo "browsable=yes" >> /etc/samba/smb1.conf
    echo "create mask=0664" >> /etc/samba/smb1.conf
    echo "directory mask=0775" >> /etc/samba/smb1.conf
  else
    echo "meil pole vist ikka sambat? =(" #kontrollisime conf'i asukohta, seda leidmata, tuleb tõdeda, et asjad pole päris nii nagu unistasime
fi
if(testparm -s /etc/samba/smb1.conf) #testime meie uue conf'i üle
  then
    sudo cp /etc/samba/smb.conf /etc/samba/smb.conf.old #teeme igaks juhuks veel originaalist backup'i
    sudo cp /etc/samba/smb1.conf /etc/samba/smb.conf #kirjutame meie muudatused originaaliks
    sudo /etc/init.d/smbd reload #loeme conf'i uuesti sisse
    echo "kle, läks hästi vist seekord!" #õnnitleme kasutajat, et seekord tegime poole päeva töö sekunditega.
  else
    echo "Asi on mäda, kutsu ruttu ADMIN!"
fi
